### ISSUE TITLE
smi파일을 srt로 변환할때 생선된 srt파일이 euc-kr로 생성됩니다.

### ISSUE THREAD

**Issue by Neoplanetz** [yklovett/smi2srt-Synology#2]
MD 지시에 따라 모두 설치 및 설정 완료해서 변환해보았는데 변환된 SRT 파일이 EUC-KR로 생성되서 Plex 웹 플레이어에서는 문제 없이 동작하지만, 스마트폰으로 볼시에 글씨들이 깨져서 나옵니다.
그래서 다른 SMI to SRT 변환 프로그램에서 EUC-KR -> UTF-8 로 변환된 SRT를 스마트폰에서 볼때 정상 한글 출력됩니다. 여기서 사용하는 smi to srt 변환시 EUC-KR을 UTF-8로 변경 불가능한가요?ㅠㅠ

**Comment by yklovett** [comment]
자막 깨지는 현상 관련하여 오랜기간 확인중인데 간단하게 정리해드리면

1. euc-kr 인 smi 파일이 euc-kr ko.srt 로 변환되는 것입니다.

2. 또 euc-kr 인 파일이 모두 깨지는건 아니네요. 확률상 대충 10%도 안되는 자막 파일들이 깨집니다.

3. 아래와 같은 이슈가 있으니, 혹시 Plex server 를 1.15로 올리셨다면 1.14로 내리시거나
폰트를 1.14껄로 복구하시거나 권한을 변경해보세요.

https://forums.plex.tv/t/latest-version-of-pms-doesnt-support-subtitle-korean/387335/13

This issue appears to be caused by an error in our build process causing the files to have incorrect permissions. We’ll fix it in an upcoming release, but in the interim, you can run sudo chmod 644 [/path/to/PMS]/Resources/Fonts/*.tt* to work around it.

sudo chmod 644 [/path/to/PMS]/Resources/Fonts/*.tt*

**Comment by Neoplanetz** [comment]
@yklovett 답변 감사합니다.

일단 제 상황은 1.15.3.876와 1.14 모두 테스트 해보았고, 1.15에서는 Fonts 폴더의 폰트 파일들 권한을 아예 777로 다 줬고 실행해봤지만 동일합니다. 다른분들과는 다르게 ㅁㅁㅁ 현상은 지금 없는 상황이고
 글씨가 아예 깨지는걸로 봐서는 EUC-KR과 UTF-8 인코딩 사이에 문제가 발생한것 같습니다.
Plex 웹플레이어로는 SMI EUC-KR을 SRT EUC-KR 로 변환한 SRT 자막파일을 보는데 문제 없지만,
제 스마트폰인 아이폰으로 보았을경우 EUC-KR 인코딩의 SRT 자막은 아래 첨부한 사진과 같이 100% 깨집니다. (저는 10% 확률이 아니라 100% 네요 ㅠㅠ). 그래서 smi2srt 변환할때 SMI EUC-KR자막 파일을
SRT UTF-8로 변환하면 웹, 스마트폰 모두 한글로 잘 나오더라구요. 그리고 이건 번외 얘기인데, SMI 자막 파일의 <BR> 태그가 있을시, SRT 로 변환하셨을때 <BR> 태그가 정상적으로 한줄 아래로 적용되시는가요? 저 같은경우는 <BR> 태그가 그냥 띄어쓰기도 없이 윗줄 자막이랑 붙어서 출력되더군요.

 @yklovett 님은 스마트폰, 안드로이드, 웹 플레이어 모두에서 정상적으로 한글이 출력되시는지요?

![plex](https://user-images.githubusercontent.com/9695835/55698380-79b64900-5a00-11e9-9e46-2508c1759e1e.png)

**Comment by yklovett** [comment]
내부망의 애플TV 4k, 아이폰, 외부망에서의 맥북 Plex Player 모두 정상 동작하는걸 전제로 하고
외부망의 아이폰 (트랜스코딩이 걸릴 때) 에서만 두가지 케이스가 있습니다.

1. charset 에 상관없이 100%의 파일들이 외부망에 있는 아이폰에서 정상 재생됩니다.

2. 아이폰 Plex 플레이어 옵션에서 **Enhanced video player (beta)** 를 활성화하면
약 10%의 확률로 캡쳐해주신 화면처럼 깨집니다.

이 때는 외부 프로그램으로 encoding type 을 바꾸니 괜찮은데,
NAS 내부에서 iconv 를 통해 charset 을 UTF-8로 바꾸면 그대로 깨집니다.

차라리 @Neoplanetz  님처럼 EUC-KR 이 전부 다 깨지면 테스트도 편할텐데
어떤 파일이 깨지는지를 외부망에서 아이폰으로 재생해보지 않으면 도무지 알수가 없다는게 함정이네요.

실은 이슈 등록해주셔서 오전에 시간날때마다
chardetect 로 charset 확인하고, utf-8 이 아니면 piconv 로 변환하도록 스크립트를 수정하고
chardetect 로 잘 바뀌는것까지 테스트 끝냈는데... 막상 재생해보니 깨지던 자막은 그대로 깨지길래
github 에는 업데이트 안해두었습니다.

NAS에서 스크립트로 charset 바꾸는걸 조금 더 봐야할거같아요.

**Comment by Neoplanetz** [comment]
@yklovett 네 답변 감사드립니다. 말씀하신것 처럼 2번의 Enhanced Video Player를 비활성화 했더니 EUC-KR SRT 자막도 정상적으로 한글로 출력이 되네요~ 감사합니다.

그리고 저 같은경우는 내부망이나 외부망이나 모두 자막이 깨지는 현상이 발견되었습니다. 물론 위에 Enhanced video player 를 비활성화 하면 외부망에서는 정상 출력됩니다.

혹시 \<BT\> 태그 관련사항은 혹시 겪어 보셨는가요?

**Comment by yklovett** [comment]
@Neoplanetz 아 드디어 찾았네요 ㅎㅎ
Enhanced video player에서 깨지는 문제가 charset 이 맞았습니다.

그렇게 깨지는 자막들은 NAS에 터미널로 붙어서 그냥 vi 로 열어도 아래처럼 파일이 깨지네요

989
02:25:06,986 --> 02:25:08,715
±Â³ªÀÕ, ·ÎÀÌ½º

990
02:27:10,109 --> 02:27:15,411
 Å©¸®½ºÅäÆÛ ¸®ºê¿¡°Ô
ÀÌ ¿µÈ­¸¦ ¹ÙÄ¨´Ï´Ù


변환하고 나니 vi 로 열어도 잘나오고 Enhanced Video Player 활성화해도 잘 나옵니다.
989
02:25:06,986 --> 02:25:08,715
굿나잇, 로이스

990
02:27:10,109 --> 02:27:15,411
 크리스토퍼 리브에게
이 영화를 바칩니다


문제는 수동 커맨드에서는 잘먹는 변환이
환경변수때문인지 스크립트에서 재대로 변환이 안되는데 시간나는대로 해결해서 업데이트할게요.

**Comment by yklovett** [comment]
@Neoplanetz charset을 인식하여 UTF-8 로 변환하도록 수정해두었습니다.

문제있던 파일 5개정도 테스트해봤는데 Enhanced video Player에서도 잘 인식하네요.
그럼 이만
